version: '2'

services:

 db:
  image: mysql
  volumes:
    - ./mysqldb:/var/lib/mysql:rw
    - .:/localdb:rw
  ports:
    - 53306:3306
  environment:
     MYSQL_ROOT_PASSWORD: letsvoltin
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress
  command: [/localdb/run.sh]

 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db
    ports:
      - 8182:80
    environment:
       PMA_PORT: 3306
       PMA_USER: root
       PMA_PASSWORD: letsvoltin
